== Contributing to Apress Source Code

Copyright for Apress source code belongs to the author(s). However, under fair use you are encouraged to fork and contribute minor corrections and updates for the benefit of the author(s) and other readers.

== How to Contribute

* Make sure you have a GitHub account.
* Fork the repository for the relevant book.
* Create a new branch on which to make your change, e.g. 
`git checkout -b my_code_contribution`
* Commit your change. Include a commit message describing the correction. Please note that if your commit message is not clear, the correction will not be accepted.
* Submit a pull request.

Thank you for your contribution!

== Current list of contributors

The list below contains the list of people that have found errors in the previous edition of the book and submitted them to the author and made sure the second edition was better.

* https://github.com/rafalnowicki116[Rafal Nowicki]
* https://github.com/Affid[Affid Fedorov]
* https://github.com/Norlandz