DROP TABLE IF EXISTS SINGER;

CREATE TABLE SINGER (
    ID INT NOT NULL AUTO_INCREMENT
    , FIRST_NAME VARCHAR(60) NOT NULL
    , LAST_NAME VARCHAR(40) NOT NULL
    , BIRTH_DATE DATE
    , UNIQUE UQ_SINGER_1 (FIRST_NAME, LAST_NAME)
    , PRIMARY KEY (ID)
);
